"""Layout / ownership checks independent of device numerical validation."""
from pathlib import Path
import json, random
checks=0;max_ub=0
random.seed(12260928)
for M in range(16,65,16):
 for N in range(16,129,16):
  if M*N>4096:continue
  for S in [8,16]:
   slots=[None]*(S*64*128)
   reference=[[0]*N for _ in range(M)]
   for s in range(S):
    for m in range(M):
     for n in range(N):
      value=random.randint(-100,100)
      slots[s*64*128+m*N+n]=value
      reference[m][n]+=value
   expected=[max(r) for r in reference];rows=[None]*M
   owners=M//8;assert owners<=2*S
   for worker in range(owners):
    begin=worker*8*N;cells=8*N
    # Equivalent addresses generated by one blockCount=S strided DMA.
    values=[]
    for s in range(S):
     block=slots[begin+s*64*128:begin+s*64*128+cells]
     assert len(block)==cells and all(v is not None for v in block)
     values+=block
    width=S
    while width>1:
     count=(width//2)*cells
     values[:count]=[values[i]+values[count+i] for i in range(count)]
     width//=2
    for local in range(8):
     m=worker*8+local;assert rows[m] is None
     rows[m]=max(values[local*N:(local+1)*N])
    assert (worker*8*4)%32==0
   assert rows==expected and sum(rows)==sum(expected)
   # active and idle AIVs execute both SyncAll calls; no early return.
   max_ub=max(max_ub,S*8*N*4+2*M*4+32);checks+=1
report=dict(shape_split_pairs=checks,max_explicit_UB_bytes=max_ub,
            every_row_has_one_owner=True,only_initialized_compact_partials_read=True,
            disjoint_aligned_32B_stores=True,K_sum_before_N_max=True,
            note='Pure integer address/reduction model, not an asynchronous hardware proof')
(Path(__file__).parent/'HOST_CHECKS.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report))
